### ISSUE TITLE
Is it possible to build its own html form template and loop on tabs/fields ?

### ISSUE THREAD

**Issue by elodiegrondin** [roundhouse/Form-Builder-3#11]
Hello,
Is it possible to build its own html form template and loop on tabs/fields ?
Instead of using this : 
```{{ craft.fb.form(form) }}```

I'd like to add disabled attribute by default on my submit button.
And I'd like to change the action hidden field too but current settings don't allow to change that.

I thought I could build my own <form> and maybe call getFormByHandle and getInputHtml but the functions are not accessible in the front-end...

Is there a way to do all this?

**Comment by owldesign** [comment]
@elodiegrondin  in ersion 3.1.0 yes

via `fbForms` variable 

`craft.fbForms.yourMethod()` all public methods within `services\Forms.php` are now accessible.
