### ISSUE TITLE
Sending Conformation to Form Submitter

### ISSUE THREAD

**Issue by Bigben83** [roundhouse/Form-Builder-3#12]
Can we send a confirmation email to the submitter of the form so they have a copy of what they have submitted ?

**Comment by owldesign** [comment]
@Bigben83 update to latest version (3.1.2). Email integration now have option to send copy to sender.

![image](https://user-images.githubusercontent.com/438764/86668046-1a4e3c80-bfa7-11ea-8d31-aa71af2eadd3.png)
