### ISSUE TITLE
upgrading from craft 2 to 3 error

### ISSUE THREAD

**Issue by alexr8** [roundhouse/Form-Builder-3#13]
Hi, i get the following error when trying to install form-builder-3 on a site that was on craft 2.

*** installing form-builder
    > create table {{%formbuilder_forms}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_formbuilder_forms' already exists

Can i manually delete some tables from the db safely? I tried just deleting that table but it won't let me due to a key constraint `Cannot delete or update a parent row: a foreign key constraint fails`.

Thanks

Al

**Comment by owldesign** [comment]
You'd need to reinstall it seems. You have to remove formbuilder_entries table first before you can delete the forms table
