### ISSUE TITLE
Date formatting problem 

### ISSUE THREAD

**Issue by jolappi** [roundhouse/Form-Builder-3#14]
_unread-entries.twig gives console errors about setting date but can be fixed by 
 changing how postdates are set. 

Example below

{# set postDate = entry.dateCreated.date |timeAgo(entry.dateCreated.date) #}
{% set postDate = entry.dateCreated|date("Y-m-d") |timeAgo(entry.dateCreated|date("Y-m-d"))%}

**Comment by owldesign** [comment]
This is no longer valid, since version 3.1.0. Moving towards Craft UI and for now removing unread entries dropdown.
