### ISSUE TITLE
Receiving error after form submission when not logged into craft. Also can't access your slack channel for help.

### ISSUE THREAD

**Issue by Keishma** [roundhouse/Form-Builder-3#15]
When I submit the form on one of our clients websites. I receive the following errors:

![image](https://user-images.githubusercontent.com/33267978/85713040-db83d100-b6e0-11ea-82b2-6de51837a2dd.png)

![image](https://user-images.githubusercontent.com/33267978/85713135-f6eedc00-b6e0-11ea-825e-a9a2a2157bec.png)

The form is also failing to send, however if I am logged into craft, everything works as expected...

I tried to access the form builder slack channel, but the form on your website does not submit. 

Thanks for you help,

**Comment by owldesign** [comment]
@Keishma hi, it might be your Spam Time Method, its set too high. You'd want to set this to something much smaller, maybe few seconds. Currenly what its doing is checking if form is submitted before 1593084448 seconds have passed.

**Comment by Keishma** [comment]
Thanks for your response, after updating to latest plugin release, it is working
