### ISSUE TITLE
Latest version is not reflected in composer.json

### ISSUE THREAD

**Issue by 321zeno** [roundhouse/Form-Builder-3#21]
The latest release has the tag `3.1.4.4` but the version specified in [composer.json](https://github.com/roundhouse/Form-Builder-3/blob/3.1.4.4/composer.json) is `3.1.4.3`. This prevents me from using `3.1.4.4` in my project.
```
Your requirements could not be resolved to an installable set of packages.

The requested package roundhouse/form-builder 3.1.4.4 exists as roundhouse/form-builder[3.0.1, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.0.19, 3.0.2, 3.0.20, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.3.1, 3.1.4, 3.1.4.1, 3.1.4.2, 3.1.4.3, dev-dev, dev-integrations, dev-master, dev-salesforce] but these are rejected by your constraint.
```

![image](https://user-images.githubusercontent.com/1746890/99915716-37d53600-2cfd-11eb-951e-57843d889bcd.png)

Removing the `version` key from composer.json would prevent this issue from cropping up again.

**Comment by owldesign** [comment]
@321zeno I removed version key from composer, hopefully that should resovle your issue.
