### ISSUE TITLE
Custom Plugin UI broken in recent versions

### ISSUE THREAD

**Issue by 321zeno** [roundhouse/Form-Builder-3#22]
These screenshots are from FormBuilder version `3.1.4.3`:
![image](https://user-images.githubusercontent.com/1746890/99917804-863d0180-2d0a-11eb-82d5-6bf5fec2e61f.png)
![image](https://user-images.githubusercontent.com/1746890/99917819-981ea480-2d0a-11eb-84d5-e7b7043ccb8f.png)
As you can see, the UI is unusable.

Using FormBuilder version `3.0.20`:
![image](https://user-images.githubusercontent.com/1746890/99917835-cac89d00-2d0a-11eb-92c3-e301bea26482.png)
![image](https://user-images.githubusercontent.com/1746890/99917776-55f56300-2d0a-11eb-973d-eb270c35ba21.png)

Using Craft `3.5.10` on Google Crome.

**Comment by owldesign** [comment]
Latest version should fix this
