### ISSUE TITLE
Error upgrading from 2 to 3

### ISSUE THREAD

**Issue by sgtpenguin** [roundhouse/Form-Builder-3#23]
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'verac3.formbuilder_forms' doesn't exist
The SQL being executed was: SELECT *
FROM `formbuilder_forms`
WHERE `handle`='tellUsYourStory'`

I get this error when trying to access the settings panel `/admin/form-builder/settings`, in an effort to try to migrate forms to Craft 3.

the table should be 'craft_formbuilder_forms'  Table names are prefixed via `.env`'s `DB_TABLE_PREFIX` as was customary in Craft 2.

**Comment by elblasto** [comment]
Same here

**Comment by owldesign** [comment]
Pull latests, should be fixed now
