### ISSUE TITLE
Composer 2 issues

### ISSUE THREAD

**Issue by lenvanessen** [roundhouse/Form-Builder-3#25]
Is this repo still under active development? Composer 2 has been out quite some time, but since this repo wansn't updated recently we're experiencing problems with the autoloading:

Generating optimized autoload files
Class Pachico\Magoo\Util\Luhn located in ./vendor/pachico/magoo/src/util/luhn.php does not comply with psr-4 autoloading standard. Skipping.
Class Pachico\Magoo\Util\Utilinterface located in ./vendor/pachico/magoo/src/util/utilinterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Pachico\Magoo\Magoo located in ./vendor/pachico/magoo/src/magoo.php does not comply with psr-4 autoloading standard. Skipping.
Class Pachico\Magoo\Mask\Email located in ./vendor/pachico/magoo/src/mask/email.php does not comply with psr-4 autoloading standard. Skipping.
Class Pachico\Magoo\Mask\Regex located in ./vendor/pachico/magoo/src/mask/regex.php does not comply with psr-4 autoloading standard. Skipping.
Class Pachico\Magoo\Mask\Maskinterface located in ./vendor/pachico/magoo/src/mask/maskinterface.php does not comply with psr-4 autoloading standard. Skipping.
Class Pachico\Magoo\Mask\Creditcard located in ./vendor/pachico/magoo/src/mask/creditcard.php does not comply with psr-4 autoloading standard. Skipping.

Can this be addressed?

**Comment by owldesign** [comment]
I'm not sure how this is related to form-builder? All vendors mentioned above are outside roundhouse
