### ISSUE TITLE
Latest version not showing in the Plugin Store

### ISSUE THREAD

**Issue by olivierbon** [roundhouse/Form-Builder-3#27]
Your latest version (`3.2.0.1`) is not available in the [Plugin Store](https://plugins.craftcms.com/form-builder) at the moment. 

You need to create a new tag with each of your releases ([point 3 here](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases) for details).

**Comment by owldesign** [comment]
Not exactly sure why plugin store is not pulling latest versions or change log. Packagist seems to have it upto date https://packagist.org/packages/roundhouse/form-builder
