### ISSUE TITLE
"Object of class DateTime could not be converted to string" when submitting form with date field

### ISSUE THREAD

**Issue by nicbou** [roundhouse/Form-Builder-3#7]
When I submit a valid form with a date field, I get the following stack trace:

yii\base\ErrorException: Object of class DateTime could not be converted to string in /var/www/storage/runtime/compiled_templates/14/14dad9777bf69d6b527ea5dc1e8e2c315322ef884aab18769e8596ebecb31e15.php:233
Stack trace:
#0 /var/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(4096, 'Object of class...', '/var/www/storag...', 233)
#1 /var/www/storage/runtime/compiled_templates/14/14dad9777bf69d6b527ea5dc1e8e2c315322ef884aab18769e8596ebecb31e15.php(233): craft\web\ErrorHandler->handleError(4096, 'Object of class...', '/var/www/storag...', 233, Array)
#2 /var/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b2e0bd57d5695e3138b637a8d383754d22e140b61638ddd1d6e98fc403f070b2->doDisplay(Array, Array)
#3 /var/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/vendor/twig/twig/src/Template.php(380): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#6 /var/vendor/twig/twig/src/Template.php(392): craft\web\twig\Template->display(Array)
#7 /var/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#8 /var/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#9 /var/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('form-builder/in...', Array)
#10 /var/vendor/roundhouse/form-builder/src/services/integrations/Email.php(78): craft\web\View->renderTemplate('form-builder/in...', Array)
#11 /var/vendor/roundhouse/form-builder/src/services/integrations/Email.php(56): roundhouse\formbuilder\services\integrations\Email->_preparePayload(Array)
#12 /var/vendor/roundhouse/form-builder/src/services/Integrations.php(229): roundhouse\formbuilder\services\integrations\Email->prepare(Array, Object(roundhouse\formbuilder\elements\Entry))
#13 /var/vendor/roundhouse/form-builder/src/controllers/EntriesController.php(245): roundhouse\formbuilder\services\Integrations->performIntegrations(Object(roundhouse\formbuilder\elements\Entry), Object(roundhouse\formbuilder\elements\Form))
#14 [internal function]: roundhouse\formbuilder\controllers\EntriesController->actionSave()
#15 /var/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /var/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /var/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('save', Array)
#18 /var/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#19 /var/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('form-builder/en...', Array)
#20 /var/vendor/craftcms/cms/src/web/Application.php(566): craft\web\Application->runAction('form-builder/en...', Array)
#21 /var/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /var/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /var/www/html/index.php(21): yii\base\Application->run()
#24 {main}

**Comment by nicbou** [comment]
- I am using v3.0.17.
- Date only
- Marked as required
- No special options on the form

**Comment by nicbou** [comment]
This is still an issue in 3.0.18. Once this is fixed, we're ready to purchase and deploy Form Builder on [All About Berlin](https://allaboutberlin.com)

**Comment by owldesign** [comment]
@nicbou please pull latest version, that should fix it.
