### ISSUE TITLE
Date field "value" attribute has invalid format

### ISSUE THREAD

**Issue by nicbou** [roundhouse/Form-Builder-3#8]
Submit an invalid form that contains a valid date field. The form loads again, and all the submitted values are filled in. However the date field remains empty, because the "value" attribute is not in the ISO 3601 format.

This is the generated HTML:
```
<input type="date" name="fields[dateOfBirth][date]" value="9/23/1990" placeholder=" " autocomplete="off" required="" size="10">
```

This is the error I get in the Chrome console:
```
The specified value "9/23/1992" does not conform to the required format, "yyyy-MM-dd".
```

**Comment by owldesign** [comment]
Fixed, 3.0.19 should have that fixed. Please update
